### ISSUE TITLE
1.4 - Library Reference Error

### ISSUE THREAD

**Issue by behub-au** [SLOKnightfall/TorghastTourGuide#10]
Hello,

I guess the way curse packager included this library didn't work correctly.

Error:
`12x Couldn't open TorghastTourguide\Libs\AceGUI-3.0-41-SharedMediaWidgets\widget.xml`

The path includes a 'trunk' folder.

`_retail_\Interface\AddOns\TorghastTourguide\Libs\AceGUI-3.0-SharedMediaWidgets\trunk\widget.xml`

This comes down this way via the Curse client and downloading the zip manually.

**Comment by cremor** [comment]
This seems to have been fixed in 1.4.1 or 1.4.2
