### ISSUE TITLE
Power Notes field shows the Power Weight when you close and re-edit a power

### ISSUE THREAD

**Issue by filliph** [SLOKnightfall/TorghastTourGuide#12]
Step 1: Set a weight and write a note
Step 2: Click on the weight to edit it
Step 3: Not profit

Step 0:
![image](https://user-images.githubusercontent.com/9424286/109006135-a8944180-76a2-11eb-9338-bdd901666fd8.png)

Step 1:
![image](https://user-images.githubusercontent.com/9424286/109006194-b77af400-76a2-11eb-80cf-0bfd470d7aaa.png)

Step 1.5:
![image](https://user-images.githubusercontent.com/9424286/109006223-bfd32f00-76a2-11eb-9f92-bd2427d16d20.png)

Step 2:
![image](https://user-images.githubusercontent.com/9424286/109006254-c95c9700-76a2-11eb-91ae-0f578f8d0665.png)

**Comment by SLOKnightfall** [comment]
Fixed in next version
