### ISSUE TITLE
Error on anima cells

### ISSUE THREAD

**Issue by ghost** [SLOKnightfall/TorghastTourGuide#14]
1x TorghastTourguide\Modules\Powers.lua:144: bad argument #1 to 'ipairs' (table expected, got nil)
[string "=[C]"]: in function `ipairs'
[string "@TorghastTourguide\Modules\Powers.lua"]:144: in function <TorghastTourguide\Modules\Powers.lua:142>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by SLOKnightfall** [comment]
Fixed in next update
