### ISSUE TITLE
The addon prevents showing anima powers in combat

### ISSUE THREAD

**Issue by cremor** [SLOKnightfall/TorghastTourGuide#16]
When this addon is enabled and you pick up an anima orb during combat, the powers are not shown. The show/hide button is there, but the actual powers are not visible/selectable.

This is a new problem in 9.1.
The addon was at version 2.1.1 when this happend.
No Lua errors were captured by BugGrabber/BugSack - not even a taint error.

**Comment by SLOKnightfall** [comment]
Fixed in the next Update
