### ISSUE TITLE
Failed Bonus Spam

### ISSUE THREAD

**Issue by lilflea12** [SLOKnightfall/TorghastTourGuide#17]
Just loaded the current release 2.3.1 (8/1/21).  and when you fail a bonus (such as Highlander), it spams that failed message over and over again.

**Comment by laric** [comment]
Failed Bouns even. I guess it is supposed to be bonus.
Got like several hundred messages with Failed Bouns: Pauper

**Comment by Tamis2Hamis** [comment]
I had this occur today with Fortified.

**Comment by SLOKnightfall** [comment]
Updated to make sure it only shows messaging once.
