### ISSUE TITLE
Frame strata is too high

### ISSUE THREAD

**Issue by cremor** [SLOKnightfall/TorghastTourGuide#23]
As you can see in this screenshot, the frame strata of the score frame and the icons on the default frame is too high. Those things are shown in front of my bag addon, but should be in the back.
The addon should create frames at the same frame strata as the default UI's Torghast frame uses.

![WoWScrnShot_080821_110444](https://user-images.githubusercontent.com/116314/128627064-5cd4026f-48dd-418c-9fd3-61886390587d.jpg)

**Comment by SLOKnightfall** [comment]
Fixed in next update
