### ISSUE TITLE
v2.4 causing errors. \Tracker.lua:371: attempt to index field 'TrackerMessages' (a boolean value)

### ISSUE THREAD

**Issue by Ookami313** [SLOKnightfall/TorghastTourGuide#24]
Updated to v2.4 and upon entering Torghast I was constantly getting the following error about every second. Had to tab out, rename the current addon folder, restore the old version from the recycle bin and reload before the errors stopped. Thanks.

37x TorghastTourguide\Modules\Tracker.lua:371: attempt to index field 'TrackerMessages' (a boolean value)
[string "@TorghastTourguide\Modules\Tracker.lua"]:371: in function `FlagFail'
[string "@TorghastTourguide\Modules\Tracker.lua"]:452: in function `CheckBonus'
[string "@TorghastTourguide\TorghastTourguide-V2.4.lua"]:711: in function `EventHandler'
[string "@TorghastTourguide\TorghastTourguide-V2.4.lua"]:457: in function <...rfaceTorghastTourguide\TorghastTourguide.lua:457>

Locals:
self = <table> {
 GetBonusScore = <function> defined @TorghastTourguide\Modules\Tracker.lua:505
 FlagBonus = <function> defined @TorghastTourguide\Modules\Tracker.lua:382
 CheckBonus = <function> defined @TorghastTourguide\Modules\Tracker.lua:418
 CombatBonusChecks = <function> defined @TorghastTourguide\Modules\Tracker.lua:399
 FlagFail = <function> defined @TorghastTourguide\Modules\Tracker.lua:370
}
bonusName = "Trapmaster"
silent = nil
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'TrackerMessages' (a boolean value)"
addon = <table> {
 RareIDs = <table> {
 }
 SetDefaultModuleLibraries = <function> defined @GatherMate2\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 CheckAnimaPowers = <function> defined @TorghastTourguide\Modules\Tracker.lua:344
 EnableModule = <function> defined @GatherMate2\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 baseName = "TorghastTourguide"
 IterateEmbeds = <function> defined @GatherMate2\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 SecureHookScript = <function> defined @BetterWardrobe\Libs\AceHook-3.0\AceHook-3.0.lua:410
 CreateAnimaPowerListFrame = <function> defined @TorghastTourguide\Modules\Guide.lua:525
 RareClick = <function> defined @TorghastTourguide\Modules\Guide.lua:1059
 ClearOverview = <function> defined @TorghastTourguide\Modules\Guide.lua:1305
 RawHookScript = <function> defined @BetterWardrobe\Libs\AceHook-3.0\AceHook-3.0.lua:395
 AnimaPowers = <table> {
 }
 Printf = <function> defined @DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:69
 PowerTooltips = <function> defined @TorghastTourguide\Modules\Tooltips.lua:41
 SetDefaultModulePrototype = <function> defined @GatherMate2\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 CheckAnimaRarity = <function> defined @TorghastTourguide\Modules\Tracker.lua:365
 ravCount = 0
 defaultModuleState = true
 IsEnabled = <function> defined @GatherMate2\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 ToggleTourGuide = <function> defined @TorghastTourguide\Modules\Guide.lua:1030
 GetWidgetBonuses = <function> defined @TorghastTourguide\Modules\Tracker.lua:688
 DisableModule = <function> defined @GatherMate2\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 Stats = <table> {
 }
 UpdateItemCount = <function> defined @TorghastTourguide\TorghastTourguide.lua:976
 ToggleLinkWindow = <function> defined @TorghastTourguide\Modules\Guide.lua:1382
 RegisterMessage = <function> defined @AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetArgs = <function> defined @DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:144
 frames = <table> {
 }
 checkBonusStatus = <function> defined @TorghastTourguide\Modules\Tracker.lua:394
 hooks = <table> {
 }
 Weights_Notesdb = <table> {
 }
 Statsdb = <table> {
 }
 ZoneList = <table> {
 }
 db = <table> {
 }
 BlessingNames = <table> {
 }
 fontStrings = <table> {
 }
 TormentTips = <table> {
 }
 SetEnabledState = <function> defined @GatherMate2\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @BetterWardrobe\Libs\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 SetUpOverview = <function> defined @TorghastTourguide\Modules\Guide.lua:1314
 RegisterEvent = <function> defined @AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 InitScoreFrame = <function> defined @TorghastTourguide\Modules\Tracker.lua:524
 BossTips = <table> {
 }
 Bosses = <table> {
 }
 sortpowers = <table> {
 }
 IterateModules = <function> defined @GatherMate2\Libs\AceAddon-3.0\AceAddon-3.0.lua:437

**Comment by Cudyhouse** [comment]
Message: ...terface\AddOns\TorghastTourguide\Modules\Tracker.lua:371: attempt to index field 'TrackerMessages' (a boolean value)
Time: Tue Aug 10 15:48:04 2021
Count: 21
Stack: ...terface\AddOns\TorghastTourguide\Modules\Tracker.lua:371: attempt to index field 'TrackerMessages' (a boolean value)
[string "@Interface\AddOns\TorghastTourguide\Modules\Tracker.lua"]:371: in function `FlagFail'
[string "@Interface\AddOns\TorghastTourguide\Modules\Tracker.lua"]:452: in function `CheckBonus'
[string "@Interface\AddOns\TorghastTourguide\TorghastTourguide.lua"]:711: in function `EventHandler'
[string "@Interface\AddOns\TorghastTourguide\TorghastTourguide.lua"]:457: in function <...rface\AddOns\TorghastTourguide\TorghastTourguide.lua:457>

Locals: self = <table> {
 GetBonusScore = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Tracker.lua:505
 FlagBonus = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Tracker.lua:382
 CheckBonus = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Tracker.lua:418
 CombatBonusChecks = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Tracker.lua:399
 FlagFail = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Tracker.lua:370
}
bonusName = "Trapmaster"
silent = nil
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'TrackerMessages' (a boolean value)"
addon = <table> {
 RareIDs = <table> {
 }
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 CheckAnimaPowers = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Tracker.lua:344
 EnableModule = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 baseName = "TorghastTourguide"
 IterateEmbeds = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 SecureHookScript = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:410
 CreateAnimaPowerListFrame = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Guide.lua:525
 RareClick = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Guide.lua:1059
 ClearOverview = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Guide.lua:1305
 RawHookScript = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:395
 AnimaPowers = <table> {
 }
 Printf = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceConsole\AceConsole-3.0.lua:69
 PowerTooltips = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Tooltips.lua:41
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 CheckAnimaRarity = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Tracker.lua:365
 ravCount = 0
 defaultModuleState = true
 IsEnabled = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 ToggleTourGuide = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Guide.lua:1030
 GetWidgetBonuses = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Tracker.lua:688
 DisableModule = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 Stats = <table> {
 }
 UpdateItemCount = <function> defined @Interface\AddOns\TorghastTourguide\TorghastTourguide.lua:976
 ToggleLinkWindow = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Guide.lua:1382
 RegisterMessage = <function> defined @Interface\AddOns\Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetArgs = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceConsole\AceConsole-3.0.lua:144
 frames = <table> {
 }
 checkBonusStatus = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Tracker.lua:394
 hooks = <table> {
 }
 Weights_Notesdb = <table> {
 }
 Statsdb = <table> {
 }
 ZoneLis
