### ISSUE TITLE
Lua errors v2.6.1

### ISSUE THREAD

**Issue by Meilinn** [SLOKnightfall/TorghastTourGuide#32]
Since this update I get 20 lua errors as soon as I log on to the game, no matter where I am. 

Message: Interface\AddOns\TorghastTourguide\Modules\Tracker.lua:456: '=' expected near 'if'
Time: Tue Mar 15 16:20:34 2022
Count: 1
Stack: Interface\AddOns\TorghastTourguide\Modules\Tracker.lua:456: '=' expected near 'if'

Locals: 

Message: [string "TTG_CombatTimer:OnLoad"]:1: attempt to call method 'OnLoad' (a nil value)
Time: Tue Mar 15 16:20:34 2022
Count: 1
Stack: [string "TTG_CombatTimer:OnLoad"]:1: attempt to call method 'OnLoad' (a nil value)
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>

Locals: self = TTG_CombatTimer {
 0 = <userdata>
 StopwatchTickerMinute = <unnamed> {
 }
 StopwatchTickerSecond = <unnamed> {
 }
 TopBG = <unnamed> {
 }
 StopwatchTickerHour = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = TTG_CombatTimer {
 0 = <userdata>
 StopwatchTickerMinute = <unnamed> {
 }
 StopwatchTickerSecond = <unnamed> {
 }
 TopBG = <unnamed> {
 }
 StopwatchTickerHour = <unnamed> {
 }
}
(*temporary) = true
(*temporary) = "attempt to call method 'OnLoad' (a nil value)"

Message: Interface\AddOns\TorghastTourguide\Modules\Tracker.lua:456: '=' expected near 'if'
Time: Tue Mar 15 16:20:38 2022
Count: 4

Message: TTG_ScoreFrame: Has bad mixin: TTG_ScoreMixin
Time: Tue Mar 15 16:20:38 2022
Count: 4

Message: <unnamed>: Has bad mixin: TTG_GemMixin
Time: Tue Mar 15 16:20:38 2022
Count: 20

Message: Frame <unnamed>: Unknown method OnEnter in element OnEnter
Time: Tue Mar 15 16:20:38 2022
Count: 29

Message: <unnamed>: Has bad mixin: TTG_FrameMixin
Time: Tue Mar 15 16:20:38 2022
Count: 4

Message: Frame <unnamed>: Unknown method OnLeave in element OnLeave
Time: Tue Mar 15 16:20:38 2022
Count: 6

Message: <unnamed>: Has bad mixin: TTG_TimerMixin
Time: Tue Mar 15 16:20:38 2022
Count: 3

Message: Frame <unnamed>: Unknown method OnLoad in element OnLoad
Time: Tue Mar 15 16:20:38 2022
Count: 3

Message: <unnamed>: Has bad mixin: TTG_ScoreMixin
Time: Tue Mar 15 16:20:38 2022
Count: 3

Message: Frame <unnamed>: Unknown method OnClick in element OnClick
Time: Tue Mar 15 16:20:38 2022
Count: 3

Message: Frame TTG_ScoreFrame: Unknown method OnLoad in element OnLoad
Time: Tue Mar 15 16:20:38 2022
Count: 3

Message: Frame TTG_ScoreFrame: Unknown method OnDragStart in element OnDragStart
Time: Tue Mar 15 16:20:38 2022
Count: 3

Message: Frame TTG_ScoreFrame: Unknown method OnDragStop in element OnDragStop
Time: Tue Mar 15 16:20:38 2022
Count: 3

Message: TTG_BonusList: Has bad mixin: TTG_BonusListMixin
Time: Tue Mar 15 16:20:38 2022
Count: 3

Message: Frame TTG_BonusList: Unknown method OnShow in element OnShow
Time: Tue Mar 15 16:20:38 2022
Count: 3

Message: TTG_CombatTimer: Has bad mixin: TTG_TimerMixin
Time: Tue Mar 15 16:20:38 2022
Count: 3

Message: Frame TTG_CombatTimer: Unknown method OnHide in element OnHide
Time: Tue Mar 15 16:20:38 2022
Count: 3

Message: ...rface\AddOns\TorghastTourguide\TorghastTourguide.lua:612: attempt to call method 'Stop' (a nil value)
Time: Tue Mar 15 16:20:38 2022
Count: 1
Stack: ...rface\AddOns\TorghastTourguide\TorghastTourguide.lua:612: attempt to call method 'Stop' (a nil value)
[string "@Interface\AddOns\TorghastTourguide\TorghastTourguide.lua"]:612: in function <...rface\AddOns\TorghastTourguide\TorghastTourguide.lua:611>

Locals: (*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 StopwatchTickerMinute = <unnamed> {
 }
 StopwatchTickerSecond = <unnamed> {
 }
 par = <unnamed> {
 }
 StopwatchTickerHour = <unnamed> {
 }
}
(*temporary) = "attempt to call method 'Stop' (a nil value)"
addon = <table> {
 RareIDs = <table> {
 }
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 EnableModule = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 baseName = "TorghastTourguide"
 IterateEmbeds = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 SecureHookScript = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:410
 CreateAnimaPowerListFrame = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Guide.lua:560
 RareClick = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Guide.lua:1232
 ClearOverview = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Guide.lua:1478
 RawHookScript = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:395
 AnimaPowers = <table> {
 }
 Printf = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceConsole-3.0\AceConsole-3.0.lua:69
 PowerTooltips = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Tooltips.lua:41
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 ravCount = 0
 defaultModuleState = true
 IsEnabled = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 ToggleTourGuide = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Guide.lua:1203
 DisableModule = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 Stats = <table> {
 }
 UpdateItemCount = <function> defined @Interface\AddOns\TorghastTourguide\TorghastTourguide.lua:1188
 ToggleLinkWindow = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Guide.lua:1555
 RegisterMessage = <function> defined @Interface\AddOns\TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetArgs = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceConsole-3.0\AceConsole-3.0.lua:144
 frames = <table> {
 }
 hooks = <table> {
 }
 db = <table> {
 }
 fontStrings = <table> {
 }
 SetEnabledState = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 RegisterEvent = <function> defined @Interface\AddOns\TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 PowerNames = <table> {
 }
 FavoritePowerdb = <table> {
 }
 Weights_Notesdb = <table> {
 }
 Statsdb = <table> {
 }
 IterateModules = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 CurrentPhantasma = <function> defined @Interface\AddOns\TorghastTourguide\TorghastTourguide.lua:671
 RawHook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:313
 TormentTips = <table> {
 }
 BlessingNames = <table> {
 }
 BlessingTips = <table> {
 }
 SetUpBoxFrame = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Guide.lua:1313
 mobs = <table> {
 }
 CreateRareButtons = <function> defined @Interface\AddOns\TorghastTourguide\Modules\Guide.lua:1126
 BossTips = <table> {
 }
 Bosses = <table> {
 }
 OnInitialize = <function> defined @Interf

**Comment by SLOKnightfall** [comment]
Fixed in the 2.6.2 build
