### ISSUE TITLE
Text overlap for Ravenous Anima Cell powers in localized WoW 

### ISSUE THREAD

**Issue by cremor** [SLOKnightfall/TorghastTourGuide#4]
Localized WoW versions have overlapping text on the Ravenous Anima Cell powers page. See screenshot:

![WoWScrnShot_012921_162036](https://user-images.githubusercontent.com/116314/106298529-48051680-6254-11eb-9437-bcf1676abb03.jpg)

**Comment by SLOKnightfall** [comment]
Should be fixed in V1.2
