### ISSUE TITLE
PowerData.lua:54: attempt to compare string with nil

### ISSUE THREAD

**Issue by Ookami313** [SLOKnightfall/TorghastTourGuide#5]
Updated to 1.2.1 and received the following error when I logged into the game.

1x TorghastTourguide\Data\PowerData.lua:54: attempt to compare string with nil
[string "@TorghastTourguide\Data\PowerData.lua"]:54: in function <TorghastTourguide\Data\PowerData.lua:47>
[string "=[C]"]: in function `sort'
[string "@TorghastTourguide\Data\PowerData.lua"]:47: in function <TorghastTourguide\Data\PowerData.lua:46>

Locals:
source1 = 331197
source2 = 315300
(*temporary) = "Soulforge Embers"
(*temporary) = nil
(*temporary) = "attempt to compare string with nil"
addon = <table> {
 RareIDs = <table> {
 }
 SetDefaultModuleLibraries = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 InitPowers = <function> defined @TorghastTourguide\Modules\Powers.lua:15
 EnableModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 baseName = "TorghastTourguide"
 IterateEmbeds = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 SecureHookScript = <function> defined @CovenantForge\Libs\AceHook-3.0\AceHook-3.0.lua:410
 CreateAnimaPowerListFrame = <function> defined @TorghastTourguide\Modules\Guide.lua:484
 RareClick = <function> defined @TorghastTourguide\Modules\Guide.lua:829
 ClearOverview = <function> defined @TorghastTourguide\Modules\Guide.lua:898
 RawHookScript = <function> defined @CovenantForge\Libs\AceHook-3.0\AceHook-3.0.lua:395
 AnimaPowers = <table> {
 }
 Printf = <function> defined @DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:69
 PowerTooltips = <function> defined @TorghastTourguide\Modules\Tooltips.lua:41
 SetDefaultModulePrototype = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 ravCount = 0
 defaultModuleState = true
 IsEnabled = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 ToggleTourGuide = <function> defined @TorghastTourguide\Modules\Guide.lua:800
 DisableModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 Stats = <table> {
 }
 UpdateItemCount = <function> defined @TorghastTourguide\TorghastTourguide.lua:630
 ToggleLinkWindow = <function> defined @TorghastTourguide\Modules\Guide.lua:975
 RegisterMessage = <function> defined @AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetArgs = <function> defined @DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:144
 hooks = <table> {
 }
 db = <table> {
 }
 EditWeight = <function> defined @TorghastTourguide\Modules\Powers.lua:96
 SetEnabledState = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @CovenantForge\Libs\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 RegisterEvent = <function> defined @AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 IterateModules = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 Statsdb = <table> {
 }
 RawHook = <function> defined @CovenantForge\Libs\AceHook-3.0\AceHook-3.0.lua:313
 CreateRareButtons = <function> defined @TorghastTourguide\Modules\Guide.lua:727
 OnInitialize = <function> defined @TorghastTourguide\TorghastTourguide.lua:403
 RegisterChatCommand = <function> defined @DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:85
 GetModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 ShowTooltip = <function> defined @TorghastTourguide\TorghastTourguide.lua:483
 BossCamera = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 optionsFrame = <unnamed> {
 }
 UnregisterChatCommand = <function> defined @DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:111
 Weights_Notesdb = <table> {
 }
 SetUpOverview = <function> defined @TorghastTourguide\Modules\Guide.lua:907
 GetName = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 CreateBossButtons = <function> defined @TorghastTourguide\Modules\Guide.lua:677
 sortpowers = <table> {
 }
 ResetDB = <function> defined @TorghastTourguide\Modu

**Comment by SLOKnightfall** [comment]
should be fixed in next update
