### ISSUE TITLE
Index of nil value error in Powers.lua

### ISSUE THREAD

**Issue by cremor** [SLOKnightfall/TorghastTourGuide#7]
I got the following error with version 1.2.2 when I hovered over the very first anima power selection screen in a Torghast run:

```
1x TorghastTourguide\Modules\Powers.lua:173: attempt to index field '?' (a nil value)
[string "@TorghastTourguide\Modules\Powers.lua"]:173: in function <TorghastTourguide\Modules\Powers.lua:153>
```

edit: Seems like I get the error for every anima power selection.

**Comment by SLOKnightfall** [comment]
Fixed in next release
